### reg
POST http://localhost:8080/my-clothes
Content-Type: application/json

{
  "email" : "22rkdmin@naver.cm",
  "seasonList" : [
    {
      "seasonName" : "봄",
      "nameList" : ["가디건", "후드티"]
    },
    {
      "seasonName" : "겨울",
      "nameList" : ["패딩", "니트/스웨터"]
    }
  ]
}
