### 댓글 목록 조회
GET http://localhost:8080/articles/5/comments
Accept: application/json

### 댓글 작성
POST http://localhost:8080/articles/5/comment/new
Content-Type: application/json

{
  "nickname": "홍길동",
  "body": "댓글 입니다."
}

### 댓글 수정
PATCH http://localhost:8080/articles/comment/5/edit
Content-Type: application/json

{
  "nickname": "홍길동 수정",
  "body": "댓글 수정."
}

### 댓글 삭제
DELETE http://localhost:8080/articles/comment/4/delete