### 댓글 목록 조회
GET http://localhost:8080/articles/5/comments
Accept: application/json

### 게시글 id로 읽기
GET http://localhost:8080/articles/4
Accept: application/json

### 댓글 작성
POST http://localhost:8080/articles/5/comment/new
Content-Type: application/json

{
  "nickname": "홍길동",
  "body": "댓글 입니다."
}

### 게시판 수정
PATCH http://localhost:8080/articles/12/edit
Content-Type: application/json

{
  "title": "게시글 수정",
  "content": "게시글 수정 입니다."
}

### 게시판 삭제
DELETE http://localhost:8080/articles/2/delete