### 회원가입
POST http://localhost:8080/join
Content-Type: application/json

{
  "username": "123@123",
  "password": "abc123!!",
  "gender" : "남성",
  "age": 2,
  "height": 5,
  "weight" : 4,
  "styleList" : ["댄디"]
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "123@123",
  "password": "abc123!!"
}

### 회원 스타일 수정
POST http://localhost:8080/my-style
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjNAMTIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NzA0MzQ5MTYsImV4cCI6MTY3MDQzODUxNn0.JwMYredLTBwmpl7VQxi68keGh-fDSgag2uhOgcqipRyUTjEAsHaTCGbw3pB-zuwNc15aHgM-4fDyvMLfU0Ubzw
Content-Type: application/json

{
  "styleList" : ["댄디", "놈코어"]
}

### 비밀번호 변경
POST http://localhost:8080/change-password
Content-Type: application/json

{
  "email": "22rkdmin@naver.com",
  "password": "a12345678!",  "newPassword": "a1234567!"
}
