### create
POST http://localhost:8080/join
Content-Type: application/json

{
  "email": "22rkdmin@nave2r.com",
  "password": "a12345678",
  "gender" : "남성",
  "age": 1,
  "height": 1,
  "weight" : 1,
  "styleList" : ["댄디", "스트릿"]
}


### get account
GET http://localhost:8080/account/?user_id=1
Accept: application/json