### suggest1
POST http://localhost:8080/suggest1
Content-Type: application/json

{
  "lowTemp" : 1,
  "highTemp" : 1,
  "gender" : "남성"
}

### suggest2
POST http://localhost:8080/suggest2
Content-Type: application/json

{
  "lowTemp" : 1,
  "highTemp" : 1,
  "email" : "22rkdmin@naver.com"
}


### delelte account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId" : 3,
  "accountNumber" : "1000000007"
}

### get account
GET http://localhost:8080/account/?user_id=1
Accept: application/json