### suggest1-non-member
POST http://localhost:8080/suggest1-non-member
Content-Type: application/json

{
  "lowTemp" : 8,
  "highTemp" : 12,
  "gender" : "여성"
}

### suggest2
POST http://localhost:8080/suggest2
Content-Type: application/json

{
  "lowTemp" : 23,
  "highTemp" : 13,
  "email" : "22rkdmin@naver.cm"
}

### suggest3
POST http://localhost:8080/suggest3
Content-Type: application/json

{
  "lowTemp" : 18,
  "highTemp" : 18,
  "email" : "22rkdmin@naver.cm"
}
