### suggest1-non-member
POST http://localhost:8080/suggest1-non-member
Content-Type: application/json

{
  "lowTemp" : 8,
  "highTemp" : 12,
  "gender" : "여성"
}

### suggest2
POST http://localhost:8080/suggest2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjNAMTIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NzA0MzQ5MTYsImV4cCI6MTY3MDQzODUxNn0.JwMYredLTBwmpl7VQxi68keGh-fDSgag2uhOgcqipRyUTjEAsHaTCGbw3pB-zuwNc15aHgM-4fDyvMLfU0Ubzw
Content-Type: application/json

{
  "lowTemp" : 23,
  "highTemp" : 13
}

### suggest3
POST http://localhost:8080/suggest3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjNAMTIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NzA0MzQ5MTYsImV4cCI6MTY3MDQzODUxNn0.JwMYredLTBwmpl7VQxi68keGh-fDSgag2uhOgcqipRyUTjEAsHaTCGbw3pB-zuwNc15aHgM-4fDyvMLfU0Ubzw
Content-Type: application/json

{
  "lowTemp" : 11,
  "highTemp" : 18
}
